import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Providers from "./Providers";
import "./globals.css"

const poppins = Poppins({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ["latin"],
    variable: "--font-poppins",
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Video Uploader",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={poppins.variable}>
            <body className="antialiased bg-gray-200 font-poppins">
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}